blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/PandaBlitz/PandaWardrobe/discussions
    about: Have a question rather than a bug or feature idea? Start a discussion instead.